extends: default
# https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  braces: disable
  brackets: disable
  document-start: disable
  indentation:
    level: error
    indent-sequences: consistent
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy: disable
