SHELL := /usr/bin/env bash
.DEFAULT_GOAL = help

# Unify target echoing
PRINT_TARGET = @echo "[make] --> $@"

export PYTHONPATH ?= src

.PHONY: clean
clean:  ## Cleanup autogenerated code
	$(PRINT_TARGET)
	-rm -rf .mypy_cache/ build/ venv/ .coverage
	find . -type d -name '__pycache__' -print0 | xargs -0 -n 1 -t -x rm -fr
	find . -type d -name '*.egg-info' -print0 | xargs -0 -n 1 -t -x rm -fr

.PHONY: code-checks
code-checks:  ## Meta target that runs all code checks
	$(PRINT_TARGET)
	isort .
	black .
	pylint .
	mypy --install-types --check-untyped-defs .

.PHONY: code-fmt-check
code-fmt-check:  ## Check code formatting
	$(PRINT_TARGET)
	isort --check-only .
	black --check .

.PHONY: container-build-push
container-build-push:  ## Build container image and push it to the registry (GHCR)
	$(PRINT_TARGET)
ifeq ($(OWNER),)
	$(error OWNER variable is not set. Please provide it via the environment or as a Makefile variable.)
endif
ifeq ($(VERSION),)
	$(error VERSION variable is not set. Please provide it via the environment or as a Makefile variable.)
endif
ifeq ($(GHCR_PAT),)
	$(error GHCR_PAT variable is not set. Please provide it via the environment or as a Makefile variable.)
endif
	docker buildx build \
		--build-arg BUILD_DATETIME=$(shell date -u +%FT%T%z) \
		--build-arg CONTAINER_IMAGE_VERSION=${VERSION} \
		--build-arg VCS_REF=$(shell git log --pretty=format:'%h' -n 1) \
		--load \
		--platform linux/amd64 \
		--tag=ghcr.io/$(OWNER)/instagram-cookie-generator:$(VERSION) \
		--tag ghcr.io/$(OWNER)/instagram-cookie-generator:latest \
		.

	echo "$(GHCR_PAT)" | docker login ghcr.io -u $(OWNER) --password-stdin
	docker push ghcr.io/$(OWNER)/instagram-cookie-generator:$(VERSION)
	docker push ghcr.io/$(OWNER)/instagram-cookie-generator:latest

.PHONY: container-test
container-test:  ## Run tests in container image
	$(PRINT_TARGET)
	docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit

.PHONY: help
help:  ## Display this help.
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[0;32m%-30s\033[0m %s\n", $$1, $$2}'

.PHONY: hooks-install
hooks-install:  ## Install pre-commit hooks
	$(PRINT_TARGET)
	pre-commit install

.PHONY: lint
lint: clean  ## Run linters
	$(PRINT_TARGET)
	mypy --install-types --check-untyped-defs .
	pylint .

.PHONY: test
test:  ## Run tests
	$(PRINT_TARGET)
	pytest
