name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please Action
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.GH_TOKEN_REPO }}

      - name: Checkout source code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Docker BuildKit
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN_REPO }}

      - name: Extract version from created tag
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "VERSION=${{ steps.release.outputs.version }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image via Makefile
        if: ${{ steps.release.outputs.release_created }}
        run: |
          make container-build-push \
            VERSION=${{ env.VERSION }} OWNER=${{ github.repository_owner }} GHCR_PAT=${{ secrets.GH_TOKEN_REPO }}
